/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5GH0ueFtiRS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import Image from "next/image";


export default function Navigator({
  src="/placeholder.svg",
  width=1920,
  height = 1080,
  alt="Background"
}) {
  return (
    (<div className="flex flex-col min-h-screen w-full">
      <div className="relative flex-1 overflow-hidden">
        <Image
          src={src}
          alt={alt}
          width={width}
          height={height}
          className="absolute inset-0 h-full w-full object-cover" />
        <div className="absolute inset-0" />
        <div
          className="relative z-10 flex h-full items-center justify-center px-4 md:px-6">
          <div className="w-full max-w-xl mt-6">
            <Input
              type="search"
              placeholder="Hányas szobába megy?"
              className="w-full rounded-full bg-white/90 px-6 py-4 text-lg focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" />
          </div>
        </div>
      </div>
    </div>)
  );
}
